### ISSUE TITLE
What are the defaults?

### ISSUE THREAD

**Issue by franciscop** [akhoury/request-promise-cache#2]
It seems these are the defaults:

```js
cacheTTL: 3600,
cacheLimit: 12,
```

Is that correct? Could we get it by writing somewhere in the documentation? I could do a PR if you want

**Comment by franciscop** [comment]
That was from the documentation, looking at the code that doesn't seem to be true.

Also, the `cacheTTL` is **highly misleading** since it makes devs believe it is in seconds (3600 is 1h in seconds), while later it is explained that it is in milliseconds. This mismatch from the docs and the code could cause some extra headaches. Want me to include this as well in a PR?

**Comment by akhoury** [comment]
sure, PRs are welcomed :)

**Comment by akhoury** [comment]
keep in mind that it's using https://github.com/akhoury/nano-cache for caching, under the hood.

**Comment by franciscop** [comment]
Sure, I'll send it ASAP. A question about same GET destination: if two requests are within the cacheTTL to the same url then only one request is sent. But what happens if one request is sent, the TTL passes, then another request is made and finally the first one responds (as in a high trafic, low/null TTL, long response times). Does it get sent twice in that situation or only once?

Maybe the question could be rephrased as, is the TTL counted from sending the request, or from receiving the response?

**Comment by akhoury** [comment]
we should probably test this, but from looking at the [source code](https://github.com/akhoury/request-promise-cache/blob/f3cf7f8983031a620c524347deea31b7f7beb21d/request-promise-cache.js#L47-L72), 
 we check if there is cached version OR if there is a loading-response __before sending the request__ - so to answer your question, the TTL is counted when sending the request, not when receiving.

Technically, this statement [`r._cache.get(cacheKey)`](https://github.com/akhoury/request-promise-cache/blob/f3cf7f8983031a620c524347deea31b7f7beb21d/request-promise-cache.js#L47) is really what's checking the cacheTTL, so the TTL is only counted is there is __already__ a stored response, NOT if there is a __loading__ response, this one does not count in the TTL at all, since it is assuming that you make concurrent requests for the same resource and in *most* cases one should not take too long to assume a TTL

**Comment by franciscop** [comment]
I was reviewing the code to make sure I document it properly, is `cacheKey` required? I assumed it would default to `url` if it was not included.

**Comment by akhoury** [comment]
well, what if you don't want to cache it? 


But I guess we can default to some hash that includes both the URL and params. 

```javascript
let hashCode = function (str) {
    // https://stackoverflow.com/a/34842797/493756
    return str.split('').reduce((prevHash, currVal) => ((prevHash << 5) - prevHash) + currVal.charCodeAt(0), 0);
  }; 

let cacheKey = hashCode(params); // as default

```

**Comment by franciscop** [comment]
If you don't want to cache it then you just don't set neither the cache time nor the cache counter (or set them to 0), which is quite intuitive IMHO. Let me fix that tomorrow and push to the PR.

**Comment by franciscop** [comment]
I think using the url itself is more intuitive and easier to debug than using a hash and from what I see from nano-cache repo it doesn't seem to have any downside.

But the issue is now with the querystring, since request accepts a large number of possible querystring types and parsing each manually seems quite complex.

**Comment by akhoury** [comment]
can you use `JSON.stringify()`? without the hashCode
